# Numpy

In [1]:
import numpy as np

### Creating arrays

In [2]:
L = [1,2,3,4]
print(np.array(L))

[1 2 3 4]


In [3]:
np.array(L)

array([1, 2, 3, 4])

In [4]:
mat = [[1,2,3], [4,5,6], [7,8,9]]
print(np.array(mat))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
print(np.arange(5, 26, 5))

[ 5 10 15 20 25]


In [9]:
ls = np.linspace(1,100,100)
ls

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [10]:
ls.shape

(100,)

In [11]:
reshape_ls = np.linspace(1,100,100).reshape(10,10)
reshape_ls

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
       [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [12]:
reshape_ls.shape

(10, 10)

### Random numbers

In [13]:
np.random.rand(5,3)

array([[0.4089185 , 0.63711514, 0.6467774 ],
       [0.30376722, 0.88810273, 0.91898927],
       [0.49842239, 0.42745122, 0.8849461 ],
       [0.50020103, 0.48824591, 0.22761926],
       [0.71405328, 0.11926941, 0.44868229]])

In [14]:
np.random.randn(4,4)

array([[ 1.54317724,  0.26866422,  0.23740614,  1.71270444],
       [-1.08229991,  1.16383781, -1.5777141 ,  0.93315018],
       [-0.11740702, -0.84044349, -0.25121947,  1.00865285],
       [ 0.30007713,  0.18735017, -0.37582215,  1.14288206]])

In [15]:
np.random.randint(0, 10, (5,3))

array([[0, 3, 4],
       [6, 2, 5],
       [7, 6, 2],
       [8, 4, 4],
       [7, 7, 7]])

In [16]:
arr = np.random.randint(1,101, 15)
print(arr)

[43 13 50 19 31 88 86  9 53 83 10  3 63 20 92]


In [17]:
np.random.randint(1,101, (10,10))

array([[ 88,   7,  55,  14,  28,  77,  40,  33,  39,  51],
       [ 48,  60,  46,  30,  63,  45,  73, 100,  40,  29],
       [ 86, 100,  67,  84,  70,  31,  17,   1,  23,  59],
       [ 13,  46,  34,  27,  57,  86,  53,  88,  97,  73],
       [ 70,  27,  66,  70,  37,  27,  91,  25,  11,  46],
       [ 61,  53,  17,  55,  34,  80,  19,  70,  48,  80],
       [ 85,  19,  52,  25,  45,  54,  26,  61,  29,  39],
       [ 51,  75,  14,  70,  46,  30,  22,  66,  19,  84],
       [ 85,  95,   9,  40,  29,  63,  88,  12,  94,  25],
       [ 94,  58,  89,  46,  43,  11,  74,  18,  20,  67]])

### Useful methods

In [18]:
arr.max()

92

In [19]:
arr.argmax()

14

In [23]:
arr.min()

3

In [24]:
arr.argmin()

11

### Array indexing

In [25]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr[8]

8

In [27]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [28]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [29]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
arr[-1]

9

In [31]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Array broadcasting

In [32]:
arr[:5] = 25
arr

array([25, 25, 25, 25, 25,  5,  6,  7,  8,  9])

In [33]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# using a "pointer" to arr
arr2 = arr[:5]
arr2[:] = 99
arr2

array([99, 99, 99, 99, 99])

In [35]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [36]:
# using a copy of arr
a = arr.copy()     # a = arr[::]
a[:] = 0
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [38]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
# python List
L = [2,3,4]
L*2

[2, 3, 4, 2, 3, 4]

In [40]:
# Numpy array
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### 2d Array (Matrix) indexing

In [41]:
arr_2d = np.arange(12).reshape(4,3)
arr_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [42]:
arr_2d[2][2]

8

In [43]:
arr_2d[2,2]

8

In [44]:
arr_2d[0]          # get a row (sample)

array([0, 1, 2])

In [45]:
arr_2d[:4, 0]    # get a column (single feature)

array([0, 3, 6, 9])

In [46]:
arr_2d[1:3, 1:]   # get a slice

array([[4, 5],
       [7, 8]])

### Appending arrays

In [47]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
b = np.random.randint(9,18, (3,3))
b

array([[13, 15, 12],
       [14, 17, 12],
       [12, 15, 16]])

In [49]:
c = np.vstack((a,b))
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [13, 15, 12],
       [14, 17, 12],
       [12, 15, 16]])

In [50]:
np.concatenate((a,b),axis=0)
## axis=0 means rows

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [13, 15, 12],
       [14, 17, 12],
       [12, 15, 16]])

In [51]:
np.hstack((a,b))

array([[ 0,  1,  2, 13, 15, 12],
       [ 3,  4,  5, 14, 17, 12],
       [ 6,  7,  8, 12, 15, 16]])

In [52]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2, 13, 15, 12],
       [ 3,  4,  5, 14, 17, 12],
       [ 6,  7,  8, 12, 15, 16]])

### Boolean (conditional) selection

In [53]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr > 5       # boolean array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [55]:
mask = arr > 5     

In [56]:
# masking values
arr[mask]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[arr>5]      # you will use this A LOT in pandas!

### Element-wise operations

In [57]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [58]:
arr2 = np.arange(6,11)
arr2

array([ 6,  7,  8,  9, 10])

In [59]:
arr + arr2

array([ 6,  8, 10, 12, 14])

In [60]:
arr*arr2

array([ 0,  7, 16, 27, 40])

In [61]:
arr + 100

array([100, 101, 102, 103, 104])

In [62]:
arr * 3

array([ 0,  3,  6,  9, 12])

In [63]:
print(arr **2)

[ 0  1  4  9 16]


### Universal functions

In [ ]:
arr_ordered = np.arange(0,101)
arr_ordered

In [ ]:
arr_ordered.shape

In [ ]:
[np.percentile(arr_ordered, [50, 75])]    # interquartile range


In [ ]:
arr = np.arange(5)
arr

In [ ]:
np.sqrt(arr)

In [ ]:
np.median(arr)

In [ ]:
np.max(arr)

In [ ]:
arr.max()

In [ ]:
arr.mean()

In [ ]:
arr.std()

In [ ]:
X = np.arange(1,26).reshape(5,5)
X

In [ ]:
X.mean(axis=1)

In [ ]:
mean = X.mean(axis = 0)
mean

In [ ]:
X.std(axis=0)

In [ ]:
X - mean

# Pandas

In [21]:
import pandas as pd

In [22]:
df = pd.read_csv("iris.csv", header=None, names = ["sepal_l", "sepal_w", "petal_l", "petal_w", "class"])
df.head()

FileNotFoundError: File b'iris.csv' does not exist

In [ ]:
df.shape

In [ ]:
df.describe()

In [ ]:
data = df.values
data