# NumPy
 
 NumPy(Numerical Python) is a linear alegbra library in Python. Why learning NumPy is important:
 

*    NumPy is very useful for performing mathematical and logical operations on Arrays. 

*    NumPy provides an abundance of useful features for operations on n-arrays and matrices in Python. 

*   NumPy is a very important library on which almost every data science or machine learning Python packages such as SciPy(Scientific Python), Mat-plotlib(plotting library), Scikit-learn, etc depends on to a reasonable extent.


**How to create 1D  (Rank 1) numpy array**

In [4]:
#import numpy as np to save us from having to type numpy every single time
import numpy as np

print ("NumPy version - " + np.version.version)

NumPy version - 1.15.4


In [25]:
#create 1D numpy array from a list
array_1d = np.array([1, 2, 3, 4, 5])

print (array_1d)

[1 2 3 4 5]


In [14]:
#create 1D numpy array from a list variable
list_1 = [11, 22, 33, 44, 55]
array_l1 = np.array(list_1)

print(array_l1)

[11 22 33 44 55]


In [2]:
#print the type of an numpy array we created
print ("Array type = " + str(type(array_1d)))

#print the data type 
print ("Data type = " + str(array_1d.dtype))

NameError: name 'array_1d' is not defined

In [19]:
#check the shape of the ndarray we created, it should have only 1 dimension
print(array_1d.shape)

(5,)


**How to create 2D (Rank 2) numpy arrays**

2 dimensional arrays are great for representing matrices wich are often used in data science

In [27]:
#create 2D numpy array
array_2 = np.array([[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]])

#print the array and the shape, shape should be 2 rows and 5 columns
print (array_2)
array_2.shape

[[ 1  2  3  4  5]
 [11 22 33 44 55]]


(2, 5)

In [5]:
#what happens if the lists passed to np.array has different lengths?

#create 2D numpy array
array_difflengths = np.array([[1, 2, 3, 4, 5], [11, 22, 33, 44]])

#print the array and the shape, shape should be 2 rows
print (array_difflengths)
array_difflengths.shape

[list([1, 2, 3, 4, 5]) list([11, 22, 33, 44])]


(2,)

**Create numpy arrays with different pre-filled values using numpy built in methods**

More documentation on Random Sampling at https://docs.scipy.org/doc/numpy-1.16.0/reference/routines.random.html


In [33]:
#create 3x3 array filled with zeros
array_0 = np.zeros((3, 3))

print (array_0)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
#create 2x2 array filled with 8.0
array_8 = np.full((2, 2), 8.0)

print (array_8)

[[8. 8.]
 [8. 8.]]


In [35]:
#create 2x3 array of ones 
array_1 = np.ones((2, 3))

print (array_1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [36]:
#create 4x4 matrix with diagonal 1s and the others 0 (identity matrix)
array_d = np.eye(4, 4)

print (array_d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [37]:
#create an array of random floats between 0 and 1 of (3, 4) shape
array_r = np.random.random((3, 4))

print (array_r)

[[0.01043611 0.30495656 0.93509598 0.4348673 ]
 [0.49063913 0.56403399 0.31410731 0.62669247]
 [0.25507215 0.99611864 0.59528836 0.5791938 ]]


In [38]:
#create an array filled with random integers from 0 to 10
array_i = np.random.randint(low = 1, high = 10, size = (2, 2))
print (array_i, '\n')

#the above is the same as this
array_i1 = np.random.randint(0, 10, (2, 2))
print (array_i1)

[[6 4]
 [6 4]] 

[[7 6]
 [7 0]]


**Indexing, Slice indexing**

We can use slice indexing to pull out sub-regions of ndarrays

More documentation can be found at https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html


In [6]:
#create 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7])
print (array_1d)

[1 2 3 4 5 6 7]


In [8]:
#because we have 1D array, we need only one index to access element at any position
#call the value at index 2
print ('element at index 2: ', array_1d[2])

#ndarrays are mutable, here we change an element at index 2 
array_1d[2] = 10
print ('element at index 2 after change: ', array_1d[2])


element at index 2:  10
element at index 2 after change:  10


In [9]:
#get the values in the range
print ('elements in the range: ', array_1d[1:3]) #a:b - including a, until (and excluding) b

#we can change values in the range as well
array_1d[1:3] = 10
print ('elements in the range after change: ', array_1d[1:3])

elements in the range:  [ 2 10]
elements in the range after change:  [10 10]


In [10]:
#for 2D arrays we will need two indexing first one for the row and second one for the column
#create 2D array
array_2d = np.array([[11, 12, 13, 14, 15, 16, 17], [21, 22, 23, 24, 25, 26, 27], [31, 32, 33, 34, 35, 36, 37]])
print ('original array: \n', array_2d, '\n')

#slicing: generates an array of the same rank
slice_row = array_2d[1:2, :] #a:b - including a, until (and excluding) b
print ('sliced array on [1:2, :]: \n', slice_row)

original array: 
 [[11 12 13 14 15 16 17]
 [21 22 23 24 25 26 27]
 [31 32 33 34 35 36 37]] 

sliced array on [1:2, :]: 
 [[21 22 23 24 25 26 27]]


In [11]:
#if we change the sliced array it will changed the original array too
slice_row[:, :] = 10

print ('sliced array: \n', slice_row, '\n')
print ('original array: \n', array_2d)


sliced array: 
 [[10 10 10 10 10 10 10]] 

original array: 
 [[11 12 13 14 15 16 17]
 [10 10 10 10 10 10 10]
 [31 32 33 34 35 36 37]]


In [12]:
#we can do the slicing for columns as well
slice_col = array_2d[:, 1:5]
print (slice_col)

[[12 13 14 15]
 [10 10 10 10]
 [32 33 34 35]]


In [13]:
#we can use filters to select just those elements which meet certain criteria 
#select the elements that are greater than 10
slice_col[slice_col>10]

array([12, 13, 14, 15, 32, 33, 34, 35])

In [14]:
#use similar logical filter to change elements in the array
#add 1 to all the odd values
slice_col[slice_col % 2 == 1] += 1
slice_col

array([[12, 14, 14, 16],
       [10, 10, 10, 10],
       [32, 34, 34, 36]])

**Arithmetic array operations**

More documentation at https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html

In [62]:
#addition can be done with the plus sign or 'add' numpy function
arr_x = np.array([[10, 20, 30], [40, 50, 60]])
arr_y = np.array([[11, 21, 31], [41, 51, 61]])

print("Array X")
print(arr_x, '\n')

print("Array Y")
print(arr_y, '\n')

print("Direct Addition")
print (arr_x + arr_y, '\n')

print("Numpy Addition")
print (np.add(arr_x, arr_y))

Array X
[[10 20 30]
 [40 50 60]] 

Array Y
[[11 21 31]
 [41 51 61]] 

Direct Addition
[[ 21  41  61]
 [ 81 101 121]] 

Numpy Addition
[[ 21  41  61]
 [ 81 101 121]]


In [63]:
#the same is with the subtraction 
print("Direct Subtraction")
print (arr_y - arr_x, '\n')

print("Numpy Subtraction")
print (np.subtract(arr_y, arr_x))

Direct Subtraction
[[1 1 1]
 [1 1 1]] 

Numpy Subtraction
[[1 1 1]
 [1 1 1]]


In [64]:
#multiplication
print("Direct Multiplication")
print (arr_x * arr_y, '\n')

print("Numpy Multiplication")
print (np.multiply(arr_x, arr_y))

Direct Multiplication
[[ 110  420  930]
 [1640 2550 3660]] 

Numpy Multiplication
[[ 110  420  930]
 [1640 2550 3660]]


In [66]:
#division
print("Direct Division")
print (arr_y / arr_x, '\n')

print("Numpy Division")
print (np.divide(arr_y, arr_x))

Direct Division
[[1.1        1.05       1.03333333]
 [1.025      1.02       1.01666667]] 

Numpy Division
[[1.1        1.05       1.03333333]
 [1.025      1.02       1.01666667]]


In [67]:
#square root

print (np.sqrt(arr_x))

[[3.16227766 4.47213595 5.47722558]
 [6.32455532 7.07106781 7.74596669]]


In [68]:
#exponent (e**x)

print (np.exp(arr_x))

[[2.20264658e+04 4.85165195e+08 1.06864746e+13]
 [2.35385267e+17 5.18470553e+21 1.14200739e+26]]


In [69]:
#power

print (np.power(arr_x, 3))

[[  1000   8000  27000]
 [ 64000 125000 216000]]


**Statistical methods**

More documentation at https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.statistics.html


In [15]:
#create random 4x6 matrix
arr = np.random.randn(4,6)
print (arr)


[[ 0.62339482 -2.06035201  0.56187958 -0.78396563  0.32954616  0.1680548 ]
 [-0.61576708  0.95376942 -0.12183849  0.91230398 -0.48097938 -1.26767681]
 [ 0.65724991 -1.19333832  2.11090547 -0.36444003 -1.04596587  0.08813761]
 [-0.57697486  0.65854938  1.15817653  0.48896628  1.04948852 -0.8456936 ]]


In [16]:
#compute the mean for all elements
print (arr.mean())

0.01680959962357444


In [17]:
#compute the mean by row
print (arr.mean(axis = 1))

[-0.19357371 -0.10336473  0.04209146  0.32208538]


In [18]:
#compute mean by column
print (arr.mean(axis = 0))

[ 0.0219757  -0.41034288  0.92728077  0.06321615 -0.03697764 -0.4642945 ]


In [74]:
#compute the median for all elements, by row or column can be done the same way as for mean
print (np.median(arr))

-0.331786774069337


In [19]:
#sum of all the elements, by row or column can be done the same way as for mean
print (np.sum(arr))

0.4034303909657866


**Read, or Write to disc**

In [22]:
np.savetxt('array.txt', X = arr, delimiter = ',')

In [23]:
np.loadtxt('array.txt', delimiter = ',')

array([[ 0.62339482, -2.06035201,  0.56187958, -0.78396563,  0.32954616,
         0.1680548 ],
       [-0.61576708,  0.95376942, -0.12183849,  0.91230398, -0.48097938,
        -1.26767681],
       [ 0.65724991, -1.19333832,  2.11090547, -0.36444003, -1.04596587,
         0.08813761],
       [-0.57697486,  0.65854938,  1.15817653,  0.48896628,  1.04948852,
        -0.8456936 ]])